# Generated by Django 4.0.6 on 2023-04-23 18:02

from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=254, null=True, unique=True, verbose_name='Name')),
                ('button_text', models.CharField(blank=True, default='Download', max_length=254, verbose_name='Button Text')),
                ('file', models.FileField(default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='Document')),
                ('show_on_page', models.BooleanField(default=True, verbose_name='Show on menu')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('parameter', models.TextField(blank=True, default='', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=254, null=True, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('file', models.ImageField(blank=True, default='', null=True, storage=resume.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Your Name')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Email Address')),
                ('subject', models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Subject')),
                ('message', models.CharField(blank=True, default='', max_length=999, verbose_name='Enter Message')),
                ('error_message', models.TextField(blank=True, default='', null=True, verbose_name='Error Message')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='RedirectSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('new_url', models.URLField(max_length=255, verbose_name='New URL')),
            ],
            options={
                'verbose_name': 'Redirect Slug',
                'verbose_name_plural': 'Redirect Slugs',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('statistic_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Statistic Type')),
                ('action', models.CharField(blank=True, default='', max_length=255, verbose_name='Action')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ('-created_date',),
            },
        ),
    ]
