# Generated by Django 4.0.6 on 2023-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedirectSlug',
        ),
    ]
