# Generated by Django 4.0.6 on 2023-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_redirectslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='button_text',
            field=models.CharField(blank=True, default='Download', max_length=255, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Email Address'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Your Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Subject'),
        ),
    ]
