# Generated by Django 4.0.6 on 2024-02-28 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_document_button_text_alter_document_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('action', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('get_params', models.JSONField(blank=True, default=dict, null=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('linux', 'Linux'), ('mac', 'Mac'), ('mobile', 'Mobile'), ('web', 'Web'), ('other', 'Other')], default='other', max_length=30)),
                ('browser', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('ie', 'IE'), ('opera', 'Opera'), ('other', 'Other')], default='other', max_length=30)),
                ('user_agent', models.TextField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
