# Generated by Django 4.0.6 on 2024-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_document_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
