# Generated by Django 4.0.6 on 2024-12-08 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_actionlog_options_alter_blockeduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
