# Generated by Django 4.0.6 on 2023-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_management', '0001_initial'),
    ]

    operations = [

        # migrations.RunSQL("""
        #     INSERT INTO link_management_redirectslug (
        #         id,
        #         slug,
        #         new_url,
        #         updated_date,
        #         created_date
        #     )
        #     SELECT
        #         id,
        #         slug,
        #         new_url,
        #         updated_date,
        #         created_date
        #     FROM
        #         core_redirectslug;
        #     SELECT setval('link_management_redirectslug_id_seq', (SELECT MAX(id) FROM link_management_redirectslug)+1);
        # """, reverse_sql="""
        #     INSERT INTO core_redirectslug (
        #         id,
        #         slug,
        #         new_url,
        #         updated_date,
        #         created_date
        #     )
        #     SELECT
        #         id,
        #         slug,
        #         new_url,
        #         updated_date,
        #         created_date
        #     FROM
        #         link_management_redirectslug;
        #     SELECT setval('core_redirectslug_id_seq', (SELECT MAX(id) FROM core_redirectslug)+1);
        # """),

    ]
