# Generated by Django 4.0.6 on 2024-04-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_management', '0003_redirectslug_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirectslug',
            options={'ordering': ('-created_at',), 'verbose_name': 'Redirect Slug', 'verbose_name_plural': 'Redirect Slugs'},
        ),
        migrations.RenameField(
            model_name='redirectslug',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='redirectslug',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
