# Generated by Django 4.0.6 on 2023-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('parameter', models.TextField(blank=True, default='', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'External Program Setting',
                'verbose_name_plural': 'External Program Settings',
                'ordering': ('name',),
            },
        ),
    ]
