# Generated by Django 4.0.6 on 2023-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_externalprogram_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('parameter', models.TextField(blank=True, default='', verbose_name='Parameter')),
                ('program', models.CharField(blank=True, default='', max_length=255, verbose_name='Program')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'External Program Log',
                'verbose_name_plural': 'External Program Logs',
                'ordering': ('-created_date',),
            },
        ),
    ]
