# Generated by Django 4.0.6 on 2023-05-06 21:01

from django.db import migrations


def create_default_values(apps, scheme_editor):
    default_data = [
        {
            'name': 'save_log',
            'description': 'This is to save log each API call.',
            'parameter': 'true',
        },
        {
            'name': 'log_error',
            'description': 'This is to log error that occurred on any API call.',
            'parameter': 'true',
        },
        {
            'name': 'banned_programs',
            'description': 'This is to check on each API call whether the program is banned or not. '
                           'Set this with program names separated by comma.',
            'parameter': 'true',
        },
        {
            'name': 'banned_ips',
            'description': 'This is to check on each API call whether the IP is banned or not. '
                           'Set this with IPs separated by comma.',
            'parameter': 'true',
        },
    ]

    model = apps.get_model('program', 'ExternalProgram')
    obj_list = [model(**data_dict) for data_dict in default_data]
    objs = model.objects.bulk_create(obj_list)


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0004_externallogs_success'),
    ]

    operations = [
        migrations.RunPython(create_default_values),
    ]
