# Generated by Django 4.0.6 on 2024-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_insert_default_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallogs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalprogram',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
