# Generated by Django 4.0.6 on 2024-04-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_externallogs_is_deleted_externalprogram_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallogs',
            options={'ordering': ('-created_at',), 'verbose_name': 'External Program Log', 'verbose_name_plural': 'External Program Logs'},
        ),
        migrations.RenameField(
            model_name='externallogs',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='externallogs',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='externalprogram',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='externalprogram',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
