# Generated by Django 4.0.6 on 2024-11-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_externallogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='externallogs',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='externallogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='externalprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='externalprogram',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='externalprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
