# Generated by Django 4.0.6 on 2023-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skilltypes',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free', max_length=255, verbose_name='Icon (Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
    ]
