# Generated by Django 4.0.6 on 2024-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_skill_name_alter_skilltypes_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecoupons',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skilltypes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
