# Generated by Django 4.0.6 on 2024-06-04 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_created_date_coursecoupons_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecoupons',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
