# Generated by Django 4.0.6 on 2024-11-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_coursecoupons_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecoupons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='coursecoupons',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='coursecoupons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='skilltypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='skilltypes',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='skilltypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
