# Generated by Django 4.0.1 on 2022-01-11 20:54

import django.core.validators
from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, default='Download', max_length=254, null=True, verbose_name='Buton Yazısı')),
                ('file', models.FileField(default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='Döküman')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Döküman',
                'verbose_name_plural': 'Döküman',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Sıralama')),
                ('header', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Özellik')),
                ('icon', models.CharField(blank=True, default='', help_text='https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free', max_length=254, null=True, verbose_name='İkon (Font Awesome)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Ayar')),
                ('description', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Açıklama')),
                ('parameter', models.TextField(blank=True, default='', null=True, verbose_name='Parametre')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Genel Ayar',
                'verbose_name_plural': 'Genel Ayarlar',
                'ordering': ('setting',),
            },
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Ayar')),
                ('description', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Açıklama')),
                ('file', models.ImageField(blank=True, default='', null=True, storage=resume.custom_storages.ImageSettingsStorage(), upload_to='', verbose_name='Görsel')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Görsel Ayar',
                'verbose_name_plural': 'Görsel Ayarlar',
                'ordering': ('setting',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Ad Soyad')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('message', models.CharField(blank=True, default='', max_length=999, verbose_name='Mesajınız')),
                ('error_message', models.TextField(blank=True, default='', null=True, verbose_name='Hata Mesajı')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Sıralama')),
                ('header', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Yetenek Adı')),
                ('percent', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Yüzdelik (%)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenek',
                'ordering': ('order',),
            },
        ),
    ]
