# Generated by Django 4.0.1 on 2022-01-11 22:13

import django.core.validators
from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, default='Download', max_length=254, null=True, verbose_name='Button Text')),
                ('file', models.FileField(default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='Document')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, default='', help_text='https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free', max_length=254, null=True, verbose_name='Icon (Font Awesome)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Description')),
                ('parameter', models.TextField(blank=True, default='', null=True, verbose_name='Parameter')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Description')),
                ('file', models.ImageField(blank=True, default='', null=True, storage=resume.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.CharField(blank=True, default='', max_length=999, verbose_name='Your Message')),
                ('error_message', models.TextField(blank=True, default='', null=True, verbose_name='Error Message')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Name')),
                ('percent', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('order',),
            },
        ),
    ]
