# Generated by Django 4.0.1 on 2022-01-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Subject'),
        ),
    ]
