# Generated by Django 4.0.1 on 2022-01-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('url', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, default='', help_text='https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free', max_length=254, null=True, verbose_name='Icon (Font Awesome)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
