# Generated by Django 4.0.1 on 2022-01-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_message_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Skill Type',
                'verbose_name_plural': 'Skill Types',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Email Address'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, default='', max_length=999, verbose_name='Enter Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Your Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Enter Subject'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.skilltypes', verbose_name='Skill Type'),
        ),
    ]
