# Generated by Django 4.0.1 on 2022-01-13 21:51

from django.db import migrations


def create_default_values(apps, scheme_editor):
    social_media_dump = [
        {
            'order': 1,
            'url': 'https://www.linkedin.com/in/BrkyMzrk/',
            'icon': '<i class="ot-circle fab fa-linkedin-in"></i>',
        },
        {
            'order': 2,
            'url': 'https://github.com/berkaymizrak',
            'icon': '<i class="ot-circle fab fa-github"></i>',
        },
        {
            'order': 3,
            'url': 'https://www.instagram.com/BrkyMzrk/',
            'icon': '<i class="ot-circle fab fa-instagram"></i>',
        },
        {
            'order': 4,
            'url': 'https://www.facebook.com/brky.mzrk/',
            'icon': '<i class="ot-circle fab fa-facebook-f"></i>',
        },
        {
            'order': 5,
            'url': 'https://usispro.com/',
            'icon': '<i class="ot-circle fas fa-link"></i>',
        },
    ]
    skill_type_dump = [
        {
            'id': 1,
            'name': 'Backend',
        },
        {
            'id': 2,
            'name': 'Frontend',
        },
        {
            'id': 3,
            'name': 'Devops',
        },
        {
            'id': 4,
            'name': 'Other',
        },
    ]
    skill_dump = [
        {
            'order': 1,
            'name': 'Python',
            'percent': '90',
            'skill_type_id': 1,
        },
        {
            'order': 2,
            'name': 'Django',
            'percent': '90',
            'skill_type_id': 1,
        },
        {
            'order': 3,
            'name': 'SQL Server',
            'percent': '90',
            'skill_type_id': 3,
        },
        {
            'order': 4,
            'name': 'PostgreSQL',
            'percent': '75',
            'skill_type_id': 3,
        },
        {
            'order': 5,
            'name': 'Apache',
            'percent': '45',
            'skill_type_id': 3,
        },
        {
            'order': 6,
            'name': 'Ngnix',
            'percent': '60',
            'skill_type_id': 3,
        },
        {
            'order': 7,
            'name': 'Docker',
            'percent': '60',
            'skill_type_id': 3,
        },
        {
            'order': 8,
            'name': 'Selenium',
            'percent': '95',
            'skill_type_id': 1,
        },
        {
            'order': 9,
            'name': 'Javascript',
            'percent': '85',
            'skill_type_id': 2,
        },
        {
            'order': 10,
            'name': 'CSS',
            'percent': '80',
            'skill_type_id': 2,
        },
        {
            'order': 11,
            'name': 'HTML',
            'percent': '100',
            'skill_type_id': 2,
        },
        {
            'order': 12,
            'name': 'SQL',
            'percent': '75',
            'skill_type_id': 3,
        },
        {
            'order': 13,
            'name': 'Git',
            'percent': '90',
            'skill_type_id': 4,
        },
        {
            'order': 14,
            'name': 'Linux',
            'percent': '55',
            'skill_type_id': 3,
        },
        {
            'order': 15,
            'name': 'Data Management',
            'percent': '90',
            'skill_type_id': 1,
        },
        {
            'order': 16,
            'name': 'MS Office Programmes',
            'percent': '90',
            'skill_type_id': 4,
        },
        {
            'order': 17,
            'name': 'Data Mining',
            'percent': '95',
            'skill_type_id': 1,
        },
        {
            'order': 18,
            'name': 'PyQt5',
            'percent': '85',
            'skill_type_id': 1,
        },
        {
            'order': 19,
            'name': 'WebdriverIO',
            'percent': '85',
            'skill_type_id': 1,
        },
        {
            'order': 20,
            'name': 'Cucumber',
            'percent': '65',
            'skill_type_id': 1,
        },
    ]
    image_setting_dump = [
        {
            'name': 'header_logo',
            'description': 'Logo in menu at top left.',
        },
        {
            'name': 'person_image',
            'description': 'Picture in home page.',
        },
        {
            'name': 'site_favicon',
            'description': 'Favicon for whole website.',
        },
        {
            'name': 'og_image',
            'description': 'og image for sharing image of Facebook, Twitter, Whatsapp etc. Watch out of image size.',
        },
    ]
    general_setting_dump = [
        {
            'name': 'home_detail_title',
            'description': 'Title for index/home page.',
            'parameter': 'Senior Software Engineer',
        },
        {
            'name': 'person_description',
            'description': 'Section of about me next to image in index page.',
            'parameter': "I have a Bachelor of Science Degree in Mechanical Engineering from Yildiz Technical University. Over the years I've been improving myself and continuing to make progress in the Python, web development, automation software and data management fields that I've done a lot of projects. I am currently developing websites for my own projects and companies I work for.",
        },
        {
            'name': 'person_name',
            'description': 'Name in index page that is large text.',
            'parameter': 'Berkay MIZRAK',
        },
        {
            'name': 'person_position',
            'description': 'Position, under name in index page.',
            'parameter': 'SENIOR SOFTWARE ENGINEER',
        },
        {
            'name': 'meta_description',
            'description': 'Site description in meta tags.',
            'parameter': 'Berkay MIZRAK is Python Software Engineer.',
        },
        {
            'name': 'site_title',
            'description': 'General site title of whole website.',
            'parameter': 'Berkay MIZRAK',
        },
        {
            'name': 'site_keywords',
            'description': 'Site keywords in meta tags.',
        },
        {
            'name': 'google_analytics_tracking_id',
            'description': 'With just adding Google Analytics tracking id, your website will be added to your account.',
        },
    ]
    models = {
        'SocialMedia': social_media_dump,
        'SkillTypes': skill_type_dump,
        'Skill': skill_dump,
        'ImageSetting': image_setting_dump,
        'GeneralSetting': general_setting_dump,
    }

    for model_name, dump_data in models.items():
        model = apps.get_model('user', model_name)
        obj_list = [model(**data_dict) for data_dict in dump_data]
        objs = model.objects.bulk_create(obj_list)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_skilltypes_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_values),
    ]
