# Generated by Django 4.0.1 on 2022-01-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220114_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=254, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This works as slug end of the url after domain. (https://berkaymizrak.com/xxxx)', max_length=254, null=True, unique=True, verbose_name='Name'),
        ),
    ]
