# Generated by Django 4.0.1 on 2022-02-13 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_document_name_alter_imagesetting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_date',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_date',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='imagesetting',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='skilltypes',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='document',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='skilltypes',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='button_text',
            field=models.CharField(blank=True, default='Download', max_length=254, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.TextField(blank=True, default='', verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free', max_length=254, verbose_name='Icon (Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, default='', max_length=254, verbose_name='URL'),
        ),
    ]
