# Generated by Django 4.0.6 on 2023-03-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_document_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('new_url', models.URLField(max_length=255, verbose_name='New URL')),
            ],
            options={
                'verbose_name': 'Redirect Slug',
                'verbose_name_plural': 'Redirect Slugs',
                'ordering': ('-created_date',),
            },
        ),
    ]
