# Generated by Django 4.0.6 on 2023-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_coursecoupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecoupons',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='coursecoupons',
            name='discount_price',
            field=models.FloatField(default=0, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='coursecoupons',
            name='original_price',
            field=models.FloatField(default=0, verbose_name='Original Price'),
        ),
    ]
