# Generated by Django 4.0.6 on 2023-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_coursecoupons_discounted_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('statistic_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Statistic Type')),
                ('action', models.CharField(blank=True, default='', max_length=255, verbose_name='Action')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ('-created_date',),
            },
        ),
    ]
