# This workflow will clear docker caches to open up space on server

name: Clear Caches

on:
  workflow_dispatch:

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear Caches
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker rmi $(docker images -q)
            docker builder prune -af
