# This workflow will deploy code to server on push to main or releases branches

name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/berkay_resume
            git pull
            docker compose -f docker-compose.prod.yml up --build -d
