# This workflow will migrate database on manual triggers

name: Migrate DB

on: workflow_dispatch

jobs:
  collectstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Migration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/berkay_resume
            docker exec app_resume python manage.py migrate --noinput
